admin_paiement:
    resource: "@AdminBundle/Controller/PaiementController.php"
    type:     annotation

admin_client_pro:
    resource: "@AdminBundle/Controller/ClientProController.php"
    type:     annotation

admin_theme:
    resource: "@AdminBundle/Resources/config/routing/theme.yml"
    prefix:     admin/theme

admin_formateur:
    resource: "@AdminBundle/Controller/FormateurController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/session

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_graph:
    resource: "@AdminBundle/Controller/GraphController.php"
    type:     annotation