admin_theme:
    resource: "@AdminBundle/Resources/config/routing/theme.yml"
    prefix:     /theme

admin_formateur:
    resource: "@AdminBundle/Controller/FormateurController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /session

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"