<?php

namespace AdminBundle\Repository;

/**
 * ClientProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientProRepository extends \Doctrine\ORM\EntityRepository
{

}
