<?php

namespace AdminBundle\Repository;

/**
 * FormateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormateurRepository extends \Doctrine\ORM\EntityRepository
{
}
